import Foundation
import Combine

enum L10nKey: String {
    case cpu, memory, disk, free
    case appMemory, wired, compressed, cached, freeMemory, swap
    case pressure, pressureNormal, pressureWarning, pressureCritical
    case metricsSettings, uiSettings, opacity, contrast
    case showCPU, showCores, showMemory, showMemoryDetails, showDisks
    case updateInterval, menuBarMenu, volumesSection, activityMonitor
    case showWindow, hideWindow, alwaysOnTop, compactWindow
    case alignMenu, alignLeft, alignRight
    case launchAtLogin, language, about, quit
    case aboutText, version, openProjectFolder, loginItemError
}

@MainActor
final class L10n: ObservableObject {
    static let shared = L10n()

    @Published var lang: String {
        didSet { UserDefaults.standard.set(lang, forKey: "AppLanguage") }
    }

    private init() {
        lang = UserDefaults.standard.string(forKey: "AppLanguage") ?? "en"
    }

    static let languages: [(code: String, name: String)] = [
        ("en", "English"),
        ("ru", "Русский"),
        ("es", "Español"),
        ("de", "Deutsch"),
        ("fr", "Français"),
        ("it", "Italiano"),
        ("pt", "Português"),
        ("zh", "中文"),
        ("ja", "日本語"),
        ("ko", "한국어"),
    ]

    func t(_ key: L10nKey) -> String {
        Self.tables[lang]?[key] ?? Self.tables["en"]![key]!
    }

    private static let tables: [String: [L10nKey: String]] = [
        "en": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Disk",
            .free: "free",
            .appMemory: "App",
            .wired: "Wired",
            .compressed: "Compressed",
            .cached: "Cached",
            .freeMemory: "Free",
            .swap: "Swap",
            .pressure: "Pressure",
            .pressureNormal: "Normal",
            .pressureWarning: "Warning",
            .pressureCritical: "Critical",
            .metricsSettings: "Metrics settings…",
            .uiSettings: "UI settings…",
            .opacity: "Opacity",
            .contrast: "Contrast",
            .showCPU: "CPU load",
            .showCores: "Per-core bars",
            .showMemory: "Memory",
            .showMemoryDetails: "Memory breakdown",
            .showDisks: "Disks",
            .updateInterval: "Update every",
            .menuBarMenu: "Menu bar",
            .volumesSection: "Volumes",
            .activityMonitor: "Open Activity Monitor",
            .showWindow: "Show window",
            .hideWindow: "Hide window",
            .alwaysOnTop: "Always on top",
            .compactWindow: "Compact window",
            .alignMenu: "Alignment",
            .alignLeft: "Left",
            .alignRight: "Right",
            .launchAtLogin: "Launch at login",
            .language: "Language",
            .about: "About…",
            .quit: "Quit",
            .version: "Version",
            .openProjectFolder: "Open project folder",
            .loginItemError: "Failed to change login item",
            .aboutText: "Real-time monitor of CPU load (per core), memory of every kind and free disk space in a small floating window.",
        ],
        "ru": [
            .cpu: "ЦП",
            .memory: "ОЗУ",
            .disk: "Диск",
            .free: "своб.",
            .appMemory: "Приложения",
            .wired: "Резидентная",
            .compressed: "Сжатая",
            .cached: "Файловый кэш",
            .freeMemory: "Свободно",
            .swap: "Подкачка",
            .pressure: "Нагрузка",
            .pressureNormal: "Обычная",
            .pressureWarning: "Повышенная",
            .pressureCritical: "Критическая",
            .metricsSettings: "Настройки метрик…",
            .uiSettings: "Настройки интерфейса…",
            .opacity: "Непрозрачность",
            .contrast: "Контраст",
            .showCPU: "Загрузка ЦП",
            .showCores: "Полоски по ядрам",
            .showMemory: "Память",
            .showMemoryDetails: "Разбивка памяти",
            .showDisks: "Диски",
            .updateInterval: "Обновлять каждые",
            .menuBarMenu: "Меню-бар",
            .volumesSection: "Тома",
            .activityMonitor: "Открыть Мониторинг системы",
            .showWindow: "Показывать окошко",
            .hideWindow: "Скрыть окошко",
            .alwaysOnTop: "Поверх всех окон",
            .compactWindow: "Компактное окошко",
            .alignMenu: "Выравнивание",
            .alignLeft: "Слева",
            .alignRight: "Справа",
            .launchAtLogin: "Запускать при входе в систему",
            .language: "Язык",
            .about: "О программе…",
            .quit: "Выход",
            .version: "Версия",
            .openProjectFolder: "Открыть папку проекта",
            .loginItemError: "Не удалось изменить автозапуск",
            .aboutText: "Мониторинг в реальном времени: загрузка процессора (по ядрам), оперативная память всех видов и свободное место на дисках в маленьком плавающем окошке.",
        ],
        "es": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "libre",
            .appMemory: "Apps",
            .wired: "Residente",
            .compressed: "Comprimida",
            .cached: "Caché de archivos",
            .freeMemory: "Libre",
            .swap: "Swap",
            .pressure: "Presión",
            .pressureNormal: "Normal",
            .pressureWarning: "Advertencia",
            .pressureCritical: "Crítica",
            .metricsSettings: "Ajustes de métricas…",
            .uiSettings: "Ajustes de interfaz…",
            .opacity: "Opacidad",
            .contrast: "Contraste",
            .showCPU: "Carga de CPU",
            .showCores: "Barras por núcleo",
            .showMemory: "Memoria",
            .showMemoryDetails: "Desglose de memoria",
            .showDisks: "Discos",
            .updateInterval: "Actualizar cada",
            .menuBarMenu: "Barra de menús",
            .volumesSection: "Volúmenes",
            .activityMonitor: "Abrir Monitor de Actividad",
            .showWindow: "Mostrar ventana",
            .hideWindow: "Ocultar ventana",
            .alwaysOnTop: "Siempre visible",
            .compactWindow: "Ventana compacta",
            .alignMenu: "Alineación",
            .alignLeft: "Izquierda",
            .alignRight: "Derecha",
            .launchAtLogin: "Abrir al iniciar sesión",
            .language: "Idioma",
            .about: "Acerca de…",
            .quit: "Salir",
            .version: "Versión",
            .openProjectFolder: "Abrir carpeta del proyecto",
            .loginItemError: "No se pudo cambiar el inicio automático",
            .aboutText: "Monitor en tiempo real de la carga de CPU (por núcleo), la memoria de todo tipo y el espacio libre en disco en una pequeña ventana flotante.",
        ],
        "de": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Laufwerk",
            .free: "frei",
            .appMemory: "Apps",
            .wired: "Reserviert",
            .compressed: "Komprimiert",
            .cached: "Dateicache",
            .freeMemory: "Frei",
            .swap: "Swap",
            .pressure: "Auslastung",
            .pressureNormal: "Normal",
            .pressureWarning: "Warnung",
            .pressureCritical: "Kritisch",
            .metricsSettings: "Metrik-Einstellungen…",
            .uiSettings: "Oberflächen-Einstellungen…",
            .opacity: "Deckkraft",
            .contrast: "Kontrast",
            .showCPU: "CPU-Auslastung",
            .showCores: "Balken pro Kern",
            .showMemory: "Speicher",
            .showMemoryDetails: "Speicher-Aufschlüsselung",
            .showDisks: "Laufwerke",
            .updateInterval: "Aktualisieren alle",
            .menuBarMenu: "Menüleiste",
            .volumesSection: "Volumes",
            .activityMonitor: "Aktivitätsanzeige öffnen",
            .showWindow: "Fenster anzeigen",
            .hideWindow: "Fenster ausblenden",
            .alwaysOnTop: "Immer im Vordergrund",
            .compactWindow: "Kompaktes Fenster",
            .alignMenu: "Ausrichtung",
            .alignLeft: "Links",
            .alignRight: "Rechts",
            .launchAtLogin: "Beim Anmelden starten",
            .language: "Sprache",
            .about: "Über…",
            .quit: "Beenden",
            .version: "Version",
            .openProjectFolder: "Projektordner öffnen",
            .loginItemError: "Autostart konnte nicht geändert werden",
            .aboutText: "Echtzeit-Überwachung von CPU-Auslastung (pro Kern), Speicher aller Arten und freiem Festplattenplatz in einem kleinen schwebenden Fenster.",
        ],
        "fr": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Disque",
            .free: "libre",
            .appMemory: "Apps",
            .wired: "Résidente",
            .compressed: "Compressée",
            .cached: "Cache fichiers",
            .freeMemory: "Libre",
            .swap: "Swap",
            .pressure: "Pression",
            .pressureNormal: "Normale",
            .pressureWarning: "Avertissement",
            .pressureCritical: "Critique",
            .metricsSettings: "Réglages des mesures…",
            .uiSettings: "Réglages de l'interface…",
            .opacity: "Opacité",
            .contrast: "Contraste",
            .showCPU: "Charge CPU",
            .showCores: "Barres par cœur",
            .showMemory: "Mémoire",
            .showMemoryDetails: "Détail de la mémoire",
            .showDisks: "Disques",
            .updateInterval: "Actualiser toutes les",
            .menuBarMenu: "Barre des menus",
            .volumesSection: "Volumes",
            .activityMonitor: "Ouvrir le Moniteur d'activité",
            .showWindow: "Afficher la fenêtre",
            .hideWindow: "Masquer la fenêtre",
            .alwaysOnTop: "Toujours au premier plan",
            .compactWindow: "Fenêtre compacte",
            .alignMenu: "Alignement",
            .alignLeft: "Gauche",
            .alignRight: "Droite",
            .launchAtLogin: "Lancer à l'ouverture de session",
            .language: "Langue",
            .about: "À propos…",
            .quit: "Quitter",
            .version: "Version",
            .openProjectFolder: "Ouvrir le dossier du projet",
            .loginItemError: "Impossible de modifier le démarrage automatique",
            .aboutText: "Surveillance en temps réel de la charge CPU (par cœur), de la mémoire sous toutes ses formes et de l'espace disque libre dans une petite fenêtre flottante.",
        ],
        "it": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "liberi",
            .appMemory: "App",
            .wired: "Residente",
            .compressed: "Compressa",
            .cached: "Cache file",
            .freeMemory: "Libera",
            .swap: "Swap",
            .pressure: "Pressione",
            .pressureNormal: "Normale",
            .pressureWarning: "Avviso",
            .pressureCritical: "Critica",
            .metricsSettings: "Impostazioni metriche…",
            .uiSettings: "Impostazioni interfaccia…",
            .opacity: "Opacità",
            .contrast: "Contrasto",
            .showCPU: "Carico CPU",
            .showCores: "Barre per core",
            .showMemory: "Memoria",
            .showMemoryDetails: "Dettaglio memoria",
            .showDisks: "Dischi",
            .updateInterval: "Aggiorna ogni",
            .menuBarMenu: "Barra dei menu",
            .volumesSection: "Volumi",
            .activityMonitor: "Apri Monitoraggio Attività",
            .showWindow: "Mostra finestra",
            .hideWindow: "Nascondi finestra",
            .alwaysOnTop: "Sempre in primo piano",
            .compactWindow: "Finestra compatta",
            .alignMenu: "Allineamento",
            .alignLeft: "Sinistra",
            .alignRight: "Destra",
            .launchAtLogin: "Avvia all'accesso",
            .language: "Lingua",
            .about: "Informazioni…",
            .quit: "Esci",
            .version: "Versione",
            .openProjectFolder: "Apri cartella del progetto",
            .loginItemError: "Impossibile modificare l'avvio automatico",
            .aboutText: "Monitoraggio in tempo reale del carico della CPU (per core), della memoria di ogni tipo e dello spazio libero su disco in una piccola finestra flottante.",
        ],
        "pt": [
            .cpu: "CPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "livres",
            .appMemory: "Apps",
            .wired: "Residente",
            .compressed: "Comprimida",
            .cached: "Cache de arquivos",
            .freeMemory: "Livre",
            .swap: "Swap",
            .pressure: "Pressão",
            .pressureNormal: "Normal",
            .pressureWarning: "Alerta",
            .pressureCritical: "Crítica",
            .metricsSettings: "Ajustes de métricas…",
            .uiSettings: "Ajustes de interface…",
            .opacity: "Opacidade",
            .contrast: "Contraste",
            .showCPU: "Carga da CPU",
            .showCores: "Barras por núcleo",
            .showMemory: "Memória",
            .showMemoryDetails: "Detalhamento da memória",
            .showDisks: "Discos",
            .updateInterval: "Atualizar a cada",
            .menuBarMenu: "Barra de menus",
            .volumesSection: "Volumes",
            .activityMonitor: "Abrir Monitor de Atividade",
            .showWindow: "Mostrar janela",
            .hideWindow: "Ocultar janela",
            .alwaysOnTop: "Sempre visível",
            .compactWindow: "Janela compacta",
            .alignMenu: "Alinhamento",
            .alignLeft: "Esquerda",
            .alignRight: "Direita",
            .launchAtLogin: "Iniciar ao fazer login",
            .language: "Idioma",
            .about: "Sobre…",
            .quit: "Sair",
            .version: "Versão",
            .openProjectFolder: "Abrir pasta do projeto",
            .loginItemError: "Não foi possível alterar a inicialização automática",
            .aboutText: "Monitoramento em tempo real da carga da CPU (por núcleo), da memória de todos os tipos e do espaço livre em disco em uma pequena janela flutuante.",
        ],
        "zh": [
            .cpu: "CPU",
            .memory: "内存",
            .disk: "磁盘",
            .free: "可用",
            .appMemory: "应用内存",
            .wired: "联动内存",
            .compressed: "已压缩",
            .cached: "文件缓存",
            .freeMemory: "空闲",
            .swap: "交换区",
            .pressure: "内存压力",
            .pressureNormal: "正常",
            .pressureWarning: "警告",
            .pressureCritical: "严重",
            .metricsSettings: "指标设置…",
            .uiSettings: "界面设置…",
            .opacity: "不透明度",
            .contrast: "对比色",
            .showCPU: "CPU 负载",
            .showCores: "每核心柱状图",
            .showMemory: "内存",
            .showMemoryDetails: "内存明细",
            .showDisks: "磁盘",
            .updateInterval: "刷新间隔",
            .menuBarMenu: "菜单栏",
            .volumesSection: "宗卷",
            .activityMonitor: "打开活动监视器",
            .showWindow: "显示窗口",
            .hideWindow: "隐藏窗口",
            .alwaysOnTop: "置顶显示",
            .compactWindow: "紧凑窗口",
            .alignMenu: "对齐",
            .alignLeft: "左",
            .alignRight: "右",
            .launchAtLogin: "登录时启动",
            .language: "语言",
            .about: "关于…",
            .quit: "退出",
            .version: "版本",
            .openProjectFolder: "打开项目文件夹",
            .loginItemError: "无法更改登录启动项",
            .aboutText: "在小型悬浮窗口中实时显示 CPU 负载（分核心）、各类内存占用和磁盘可用空间。",
        ],
        "ja": [
            .cpu: "CPU",
            .memory: "メモリ",
            .disk: "ディスク",
            .free: "空き",
            .appMemory: "アプリ",
            .wired: "確保中",
            .compressed: "圧縮済み",
            .cached: "ファイルキャッシュ",
            .freeMemory: "空き",
            .swap: "スワップ",
            .pressure: "メモリ負荷",
            .pressureNormal: "通常",
            .pressureWarning: "警告",
            .pressureCritical: "危険",
            .metricsSettings: "計測項目の設定…",
            .uiSettings: "UI設定…",
            .opacity: "不透明度",
            .contrast: "コントラスト",
            .showCPU: "CPU使用率",
            .showCores: "コア別バー",
            .showMemory: "メモリ",
            .showMemoryDetails: "メモリ内訳",
            .showDisks: "ディスク",
            .updateInterval: "更新間隔",
            .menuBarMenu: "メニューバー",
            .volumesSection: "ボリューム",
            .activityMonitor: "アクティビティモニタを開く",
            .showWindow: "ウィンドウを表示",
            .hideWindow: "ウィンドウを隠す",
            .alwaysOnTop: "常に最前面",
            .compactWindow: "コンパクト表示",
            .alignMenu: "配置",
            .alignLeft: "左",
            .alignRight: "右",
            .launchAtLogin: "ログイン時に起動",
            .language: "言語",
            .about: "このアプリについて…",
            .quit: "終了",
            .version: "バージョン",
            .openProjectFolder: "プロジェクトフォルダを開く",
            .loginItemError: "ログイン項目を変更できませんでした",
            .aboutText: "CPU使用率（コア別）、あらゆる種類のメモリ、ディスクの空き容量を小さなフローティングウィンドウでリアルタイムに表示します。",
        ],
        "ko": [
            .cpu: "CPU",
            .memory: "메모리",
            .disk: "디스크",
            .free: "여유",
            .appMemory: "앱 메모리",
            .wired: "고정됨",
            .compressed: "압축됨",
            .cached: "파일 캐시",
            .freeMemory: "여유",
            .swap: "스왑",
            .pressure: "메모리 압력",
            .pressureNormal: "보통",
            .pressureWarning: "경고",
            .pressureCritical: "위험",
            .metricsSettings: "측정 항목 설정…",
            .uiSettings: "UI 설정…",
            .opacity: "불투명도",
            .contrast: "대비",
            .showCPU: "CPU 사용량",
            .showCores: "코어별 막대",
            .showMemory: "메모리",
            .showMemoryDetails: "메모리 세부 내역",
            .showDisks: "디스크",
            .updateInterval: "업데이트 주기",
            .menuBarMenu: "메뉴 막대",
            .volumesSection: "볼륨",
            .activityMonitor: "활성 상태 보기 열기",
            .showWindow: "창 표시",
            .hideWindow: "창 숨기기",
            .alwaysOnTop: "항상 위에 표시",
            .compactWindow: "컴팩트 창",
            .alignMenu: "정렬",
            .alignLeft: "왼쪽",
            .alignRight: "오른쪽",
            .launchAtLogin: "로그인 시 시작",
            .language: "언어",
            .about: "정보…",
            .quit: "종료",
            .version: "버전",
            .openProjectFolder: "프로젝트 폴더 열기",
            .loginItemError: "로그인 항목을 변경할 수 없습니다",
            .aboutText: "CPU 사용량(코어별), 모든 종류의 메모리, 디스크 여유 공간을 작은 플로팅 창에서 실시간으로 보여줍니다.",
        ],
    ]
}

#if DEV_BUILD
// Dev-примечания для About: только в сборке с -dev, в публичный бинарник не попадают.
extension L10n {
    func devSuffix() -> String {
        lang == "ru"
            ? "Локальная dev-сборка этого компьютера.\nСобрано с помощью Claude Code.\n\nПапка проекта:\n{path}"
            : "Local dev build for this Mac.\nBuilt with Claude Code.\n\nProject folder:\n{path}"
    }
}
#endif
