import Foundation
import Combine

enum L10nKey: String {
    case cpu, gpu, memory, disk, free, used
    case showGPU, performanceCores, efficiencyCores
    case appMemory, wired, compressed, cached, freeMemory, swap
    case pressure, pressureNormal, pressureWarning, pressureCritical
    // Образовательные подсказки: всплывают при наведении на строку разбивки.
    case helpApp, helpWired, helpCompressed, helpCached, helpFree, helpSwap, helpPressure
    case metricsSettings, uiSettings, opacity, contrast
    case showCPU, showCores, showMemory, showMemoryDetails, showDisks
    case updateInterval, menuBarMenu, volumesSection, activityMonitor
    // Отслеживание папок
    case showFolders, foldersSettings, addFolder, folderPath, chooseFolder, alias, rescan, remove
    case openInFinder
    // Извлечение внешних томов. Глаголы взяты из локализаций самого Finder,
    // чтобы кнопка называлась ровно тем словом, к которому пользователь привык.
    case eject, ejectFailed
    // График истории размеров папки
    case history, historyDay, historyWeek, historyMonth, historyQuarter
    case historyEmpty, historyChange, historyNotEnough, historyClick
    case largestItems, scanning, noAccess, lastScan
    case scanNever, scanMinute, scan5Minutes, scan10Minutes, scanHourly, scanDaily
    case floatingPanel, alwaysOnTop, compactPanel
    case alignMenu, alignLeft, alignRight
    case launchAtLogin, language, about, quit
    // Проверка обновлений
    case updatesMenu, checkNow, checkAutomatically, updateAvailable
    case upToDate, checkFailed, openRelease
    case aboutText, version, openProjectFolder, loginItemError
}

@MainActor
final class L10n: ObservableObject {
    static let shared = L10n()

    @Published var lang: String {
        didSet { UserDefaults.standard.set(lang, forKey: "AppLanguage") }
    }

    private init() {
        lang = UserDefaults.standard.string(forKey: "AppLanguage") ?? "en"
    }

    static let languages: [(code: String, name: String)] = [
        ("en", "English"),
        ("ru", "Русский"),
        ("es", "Español"),
        ("de", "Deutsch"),
        ("fr", "Français"),
        ("it", "Italiano"),
        ("pt", "Português (Brasil)"),
        ("pt-PT", "Português (Portugal)"),
        ("zh", "中文"),
        ("ja", "日本語"),
        ("ko", "한국어"),
    ]

    func t(_ key: L10nKey) -> String {
        Self.tables[lang]?[key] ?? Self.tables["en"]![key]!
    }

    private static let tables: [String: [L10nKey: String]] = [
        "en": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disk",
            .free: "free",
            .used: "Used",
            .appMemory: "App",
            .wired: "Wired",
            .compressed: "Compressed",
            .cached: "Cached",
            .freeMemory: "Free",
            .swap: "Swap",
            .pressure: "Pressure",
            .pressureNormal: "Normal",
            .pressureWarning: "Warning",
            .pressureCritical: "Critical",
            .metricsSettings: "Metrics settings…",
            .uiSettings: "UI settings…",
            .opacity: "Opacity",
            .contrast: "Contrast",
            .showCPU: "CPU load",
            .showCores: "Per-core bars",
            .showMemory: "Memory",
            .showMemoryDetails: "Memory breakdown",
            .showDisks: "Disks",
            .updateInterval: "Update every",
            .menuBarMenu: "Menu bar",
            .volumesSection: "Volumes",
            .activityMonitor: "Open Activity Monitor",
            .floatingPanel: "Floating panel",
            .alwaysOnTop: "Always on top",
            .compactPanel: "Compact panel",
            .alignMenu: "Alignment",
            .alignLeft: "Left",
            .alignRight: "Right",
            .launchAtLogin: "Launch at login",
            .language: "Language",
            .about: "About…",
            .quit: "Quit",
            .version: "Version",
            .openProjectFolder: "Open project folder",
            .loginItemError: "Failed to change login item",
            .helpApp: "Memory held by running apps and their data. It is released when the app quits — or pushed into compressed memory and swap when RAM runs short.",
            .helpWired: "The kernel, drivers and anything that must never leave RAM. It can be neither compressed nor swapped out, so it is the one part macOS cannot reclaim under pressure.",
            .helpCompressed: "Inactive pages squeezed to roughly half their size instead of being written to disk. Far cheaper than swapping: unpacking happens in memory.",
            .helpCached: "Recently used files kept in otherwise idle RAM so that reopening them is instant. Handed back to apps the moment they ask for it — this is not a shortage.",
            .helpFree: "RAM not used for anything at all. macOS keeps this near zero on purpose: idle memory does no work, so spare capacity goes to the file cache instead.",
            .helpSwap: "Pages written out to disk once compression is no longer enough. Steadily growing swap is what makes a Mac feel slow.",
            .helpPressure: "The system's own verdict on whether apps are starved of memory — a more reliable signal than the used percentage.\n\nNormal — enough memory to go around.\nWarning — macOS is compressing and swapping hard to keep up; apps may start to stutter.\nCritical — memory is running out and the system may begin closing apps.",
            .showFolders: "Folders",
            .foldersSettings: "Folders…",
            .addFolder: "Add folder",
            .folderPath: "Folder path",
            .chooseFolder: "Choose in Finder",
            .alias: "Alias",
            .rescan: "Scan now",
            .remove: "Remove",
            .largestItems: "Largest items",
            .scanning: "Scanning…",
            .noAccess: "No access",
            .lastScan: "Last scan",
            .scanNever: "Do not update",
            .scanMinute: "Every minute",
            .scan5Minutes: "Every 5 minutes",
            .scan10Minutes: "Every 10 minutes",
            .scanHourly: "Every hour",
            .scanDaily: "Every day",
            .updatesMenu: "Updates",
            .checkNow: "Check now",
            .checkAutomatically: "Check automatically",
            .updateAvailable: "Update available:",
            .upToDate: "You are running the latest version.",
            .checkFailed: "Could not reach GitHub to check for updates.",
            .openRelease: "Open release page",
            .showGPU: "GPU load",
            .performanceCores: "Performance cores",
            .efficiencyCores: "Efficiency cores",
            .openInFinder: "Click to open in Finder",
            .eject: "Eject",
            .ejectFailed: "Could not eject the volume",
            .history: "History",
            .historyDay: "Day",
            .historyWeek: "Week",
            .historyMonth: "Month",
            .historyQuarter: "Quarter",
            .historyEmpty: "No measurements yet. The size is recorded on every scan.",
            .historyChange: "change",
            .historyNotEnough: "Not enough history for this range yet",
            .historyClick: "Click for size history",
            .aboutText: "Real-time monitor of CPU load (per core), memory of every kind and free disk space in a small floating window.",
        ],
        "ru": [
            .cpu: "ЦП",
            .gpu: "GPU",
            .memory: "ОЗУ",
            .disk: "Диск",
            .free: "своб.",
            .used: "Занято",
            .appMemory: "Приложения",
            .wired: "Резидентная",
            .compressed: "Сжатая",
            .cached: "Файловый кэш",
            .freeMemory: "Свободно",
            .swap: "Подкачка",
            .pressure: "Нагрузка",
            .pressureNormal: "Обычная",
            .pressureWarning: "Повышенная",
            .pressureCritical: "Критическая",
            .metricsSettings: "Настройки метрик…",
            .uiSettings: "Настройки интерфейса…",
            .opacity: "Непрозрачность",
            .contrast: "Контраст",
            .showCPU: "Загрузка ЦП",
            .showCores: "Полоски по ядрам",
            .showMemory: "Память",
            .showMemoryDetails: "Разбивка памяти",
            .showDisks: "Диски",
            .updateInterval: "Обновлять каждые",
            .menuBarMenu: "Меню-бар",
            .volumesSection: "Тома",
            .activityMonitor: "Открыть Мониторинг системы",
            .floatingPanel: "Плавающая панель",
            .alwaysOnTop: "Поверх всех окон",
            .compactPanel: "Компактная панель",
            .alignMenu: "Выравнивание",
            .alignLeft: "Слева",
            .alignRight: "Справа",
            .launchAtLogin: "Запускать при входе в систему",
            .language: "Язык",
            .about: "О программе…",
            .quit: "Выход",
            .version: "Версия",
            .openProjectFolder: "Открыть папку проекта",
            .loginItemError: "Не удалось изменить автозапуск",
            .helpApp: "Память, занятая работающими программами и их данными. Освобождается, когда приложение закрывается, а при нехватке уходит в сжатую память и подкачку.",
            .helpWired: "Ядро, драйверы и всё, что не имеет права покидать оперативную память. Её нельзя ни сжать, ни выгрузить на диск — единственная часть, которую macOS не может отобрать при нехватке.",
            .helpCompressed: "Неактивные страницы, ужатые примерно вдвое вместо записи на диск. Намного дешевле подкачки: распаковка идёт прямо в памяти.",
            .helpCached: "Недавно использованные файлы, оставленные в простаивающей памяти, чтобы открыть их снова мгновенно. Отдаётся приложениям по первому требованию — это не нехватка.",
            .helpFree: "Память, не занятая ничем. macOS намеренно держит её у нуля: простаивающая память не приносит пользы, поэтому запас уходит под файловый кэш.",
            .helpSwap: "Страницы, вытесненные на диск, когда сжатия уже не хватает. Именно растущая подкачка делает Mac медленным.",
            .helpPressure: "Вердикт самой системы, хватает ли приложениям памяти, — сигнал надёжнее процента занятого.\n\nОбычная — памяти достаточно.\nПовышенная — macOS вовсю сжимает и выгружает страницы, возможны подтормаживания.\nКритическая — память заканчивается, система может начать закрывать приложения.",
            .showFolders: "Папки",
            .foldersSettings: "Папки…",
            .addFolder: "Добавить папку",
            .folderPath: "Путь к папке",
            .chooseFolder: "Выбрать в Finder",
            .alias: "Псевдоним",
            .rescan: "Пересканировать",
            .remove: "Убрать",
            .largestItems: "Самое крупное внутри",
            .scanning: "Сканирование…",
            .noAccess: "Нет доступа",
            .lastScan: "Последний скан",
            .scanNever: "Не обновлять",
            .scanMinute: "Раз в минуту",
            .scan5Minutes: "Раз в 5 минут",
            .scan10Minutes: "Раз в 10 минут",
            .scanHourly: "Раз в час",
            .scanDaily: "Раз в сутки",
            .updatesMenu: "Обновления",
            .checkNow: "Проверить сейчас",
            .checkAutomatically: "Проверять автоматически",
            .updateAvailable: "Доступна версия:",
            .upToDate: "У вас последняя версия.",
            .checkFailed: "Не удалось связаться с GitHub для проверки обновлений.",
            .openRelease: "Открыть страницу релиза",
            .showGPU: "Загрузка GPU",
            .performanceCores: "Производительные ядра",
            .efficiencyCores: "Экономичные ядра",
            .openInFinder: "Клик — открыть в Finder",
            .eject: "Извлечь",
            .ejectFailed: "Не удалось извлечь том",
            .history: "История",
            .historyDay: "Сутки",
            .historyWeek: "Неделя",
            .historyMonth: "Месяц",
            .historyQuarter: "Квартал",
            .historyEmpty: "Измерений пока нет. Размер записывается при каждом обходе.",
            .historyChange: "изменение",
            .historyNotEnough: "Для этого диапазона истории пока не хватает",
            .historyClick: "Клик — история размера",
            .aboutText: "Мониторинг в реальном времени: загрузка процессора (по ядрам), оперативная память всех видов и свободное место на дисках в маленьком плавающем окошке.",
        ],
        "es": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "libre",
            .used: "Usado",
            .appMemory: "Apps",
            .wired: "Residente",
            .compressed: "Comprimida",
            .cached: "Caché de archivos",
            .freeMemory: "Libre",
            .swap: "Swap",
            .pressure: "Presión",
            .pressureNormal: "Normal",
            .pressureWarning: "Advertencia",
            .pressureCritical: "Crítica",
            .metricsSettings: "Ajustes de métricas…",
            .uiSettings: "Ajustes de interfaz…",
            .opacity: "Opacidad",
            .contrast: "Contraste",
            .showCPU: "Carga de CPU",
            .showCores: "Barras por núcleo",
            .showMemory: "Memoria",
            .showMemoryDetails: "Desglose de memoria",
            .showDisks: "Discos",
            .updateInterval: "Actualizar cada",
            .menuBarMenu: "Barra de menús",
            .volumesSection: "Volúmenes",
            .activityMonitor: "Abrir Monitor de Actividad",
            .floatingPanel: "Panel flotante",
            .alwaysOnTop: "Siempre visible",
            .compactPanel: "Panel compacto",
            .alignMenu: "Alineación",
            .alignLeft: "Izquierda",
            .alignRight: "Derecha",
            .launchAtLogin: "Abrir al iniciar sesión",
            .language: "Idioma",
            .about: "Acerca de…",
            .quit: "Salir",
            .version: "Versión",
            .openProjectFolder: "Abrir carpeta del proyecto",
            .loginItemError: "No se pudo cambiar el inicio automático",
            .helpApp: "Memoria ocupada por las apps en ejecución y sus datos. Se libera al cerrar la app, o pasa a memoria comprimida y swap cuando falta RAM.",
            .helpWired: "El núcleo, los controladores y todo lo que nunca puede salir de la RAM. No se puede comprimir ni enviar al disco: es la parte que macOS no puede recuperar bajo presión.",
            .helpCompressed: "Páginas inactivas reducidas casi a la mitad en lugar de escribirse en el disco. Mucho más barato que el swap: descomprimir ocurre en memoria.",
            .helpCached: "Archivos usados hace poco que se conservan en la RAM libre para reabrirlos al instante. Se devuelve a las apps en cuanto la piden: no es escasez.",
            .helpFree: "RAM que no se usa para nada. macOS la mantiene cerca de cero a propósito: la memoria ociosa no trabaja, así que el sobrante va a la caché de archivos.",
            .helpSwap: "Páginas escritas en el disco cuando la compresión ya no basta. El swap que crece sin parar es lo que hace que un Mac se sienta lento.",
            .helpPressure: "El veredicto del propio sistema sobre si a las apps les falta memoria: mejor señal que el porcentaje usado.\n\nNormal — hay memoria suficiente.\nAdvertencia — macOS comprime e intercambia a fondo para seguir el ritmo; las apps pueden dar tirones.\nCrítica — la memoria se agota y el sistema puede empezar a cerrar apps.",
            .showFolders: "Carpetas",
            .foldersSettings: "Carpetas…",
            .addFolder: "Añadir carpeta",
            .folderPath: "Ruta de la carpeta",
            .chooseFolder: "Elegir en Finder",
            .alias: "Alias",
            .rescan: "Analizar ahora",
            .remove: "Quitar",
            .largestItems: "Elementos más grandes",
            .scanning: "Analizando…",
            .noAccess: "Sin acceso",
            .lastScan: "Último análisis",
            .scanNever: "No actualizar",
            .scanMinute: "Cada minuto",
            .scan5Minutes: "Cada 5 minutos",
            .scan10Minutes: "Cada 10 minutos",
            .scanHourly: "Cada hora",
            .scanDaily: "Cada día",
            .updatesMenu: "Actualizaciones",
            .checkNow: "Buscar ahora",
            .checkAutomatically: "Buscar automáticamente",
            .updateAvailable: "Versión disponible:",
            .upToDate: "Ya tienes la última versión.",
            .checkFailed: "No se pudo conectar con GitHub para buscar actualizaciones.",
            .openRelease: "Abrir la página de la versión",
            .showGPU: "Carga de GPU",
            .performanceCores: "Núcleos de rendimiento",
            .efficiencyCores: "Núcleos de eficiencia",
            .openInFinder: "Clic para abrir en Finder",
            .eject: "Expulsar",
            .ejectFailed: "No se pudo expulsar el volumen",
            .history: "Historial",
            .historyDay: "Día",
            .historyWeek: "Semana",
            .historyMonth: "Mes",
            .historyQuarter: "Trimestre",
            .historyEmpty: "Aún no hay mediciones. El tamaño se registra en cada análisis.",
            .historyChange: "cambio",
            .historyNotEnough: "Todavía no hay historial suficiente para este intervalo",
            .historyClick: "Clic para ver el historial de tamaño",
            .aboutText: "Monitor en tiempo real de la carga de CPU (por núcleo), la memoria de todo tipo y el espacio libre en disco en una pequeña ventana flotante.",
        ],
        "de": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Laufwerk",
            .free: "frei",
            .used: "Belegt",
            .appMemory: "Apps",
            .wired: "Reserviert",
            .compressed: "Komprimiert",
            .cached: "Dateicache",
            .freeMemory: "Frei",
            .swap: "Swap",
            .pressure: "Auslastung",
            .pressureNormal: "Normal",
            .pressureWarning: "Warnung",
            .pressureCritical: "Kritisch",
            .metricsSettings: "Metrik-Einstellungen…",
            .uiSettings: "Oberflächen-Einstellungen…",
            .opacity: "Deckkraft",
            .contrast: "Kontrast",
            .showCPU: "CPU-Auslastung",
            .showCores: "Balken pro Kern",
            .showMemory: "Speicher",
            .showMemoryDetails: "Speicher-Aufschlüsselung",
            .showDisks: "Laufwerke",
            .updateInterval: "Aktualisieren alle",
            .menuBarMenu: "Menüleiste",
            .volumesSection: "Volumes",
            .activityMonitor: "Aktivitätsanzeige öffnen",
            .floatingPanel: "Schwebendes Fenster",
            .alwaysOnTop: "Immer im Vordergrund",
            .compactPanel: "Kompaktes Fenster",
            .alignMenu: "Ausrichtung",
            .alignLeft: "Links",
            .alignRight: "Rechts",
            .launchAtLogin: "Beim Anmelden starten",
            .language: "Sprache",
            .about: "Über…",
            .quit: "Beenden",
            .version: "Version",
            .openProjectFolder: "Projektordner öffnen",
            .loginItemError: "Autostart konnte nicht geändert werden",
            .helpApp: "Speicher, den laufende Apps und ihre Daten belegen. Er wird beim Beenden frei — oder wandert bei Knappheit in komprimierten Speicher und Swap.",
            .helpWired: "Kernel, Treiber und alles, was das RAM nie verlassen darf. Es lässt sich weder komprimieren noch auslagern — der einzige Teil, den macOS unter Druck nicht zurückholen kann.",
            .helpCompressed: "Inaktive Seiten, auf etwa die Hälfte gestaucht, statt auf die Festplatte geschrieben zu werden. Viel billiger als Swap: Das Entpacken passiert im Speicher.",
            .helpCached: "Kürzlich benutzte Dateien, die im sonst ungenutzten RAM bleiben, damit sie sofort wieder öffnen. Wird zurückgegeben, sobald Apps ihn brauchen — kein Engpass.",
            .helpFree: "RAM, das überhaupt nichts tut. macOS hält es bewusst nahe null: ungenutzter Speicher leistet nichts, der Rest arbeitet lieber als Dateicache.",
            .helpSwap: "Seiten, die auf die Festplatte ausgelagert werden, sobald Komprimieren nicht mehr reicht. Stetig wachsender Swap ist der Grund, warum ein Mac zäh wirkt.",
            .helpPressure: "Das Urteil des Systems, ob Apps zu wenig Speicher haben — aussagekräftiger als die Prozentzahl.\n\nNormal — genug Speicher vorhanden.\nWarnung — macOS komprimiert und lagert kräftig aus; Apps können stocken.\nKritisch — der Speicher geht aus, das System beendet unter Umständen Apps.",
            .showFolders: "Ordner",
            .foldersSettings: "Ordner…",
            .addFolder: "Ordner hinzufügen",
            .folderPath: "Ordnerpfad",
            .chooseFolder: "Im Finder wählen",
            .alias: "Alias",
            .rescan: "Jetzt scannen",
            .remove: "Entfernen",
            .largestItems: "Größte Elemente",
            .scanning: "Wird gescannt…",
            .noAccess: "Kein Zugriff",
            .lastScan: "Letzter Scan",
            .scanNever: "Nicht aktualisieren",
            .scanMinute: "Jede Minute",
            .scan5Minutes: "Alle 5 Minuten",
            .scan10Minutes: "Alle 10 Minuten",
            .scanHourly: "Jede Stunde",
            .scanDaily: "Jeden Tag",
            .updatesMenu: "Updates",
            .checkNow: "Jetzt prüfen",
            .checkAutomatically: "Automatisch prüfen",
            .updateAvailable: "Neue Version verfügbar:",
            .upToDate: "Sie haben die neueste Version.",
            .checkFailed: "GitHub war für die Update-Prüfung nicht erreichbar.",
            .openRelease: "Release-Seite öffnen",
            .showGPU: "GPU-Auslastung",
            .performanceCores: "Leistungskerne",
            .efficiencyCores: "Effizienzkerne",
            .openInFinder: "Klicken, um im Finder zu öffnen",
            .eject: "Auswerfen",
            .ejectFailed: "Volume konnte nicht ausgeworfen werden",
            .history: "Verlauf",
            .historyDay: "Tag",
            .historyWeek: "Woche",
            .historyMonth: "Monat",
            .historyQuarter: "Quartal",
            .historyEmpty: "Noch keine Messungen. Die Größe wird bei jedem Durchlauf festgehalten.",
            .historyChange: "Änderung",
            .historyNotEnough: "Noch nicht genug Verlauf für diesen Zeitraum",
            .historyClick: "Klicken für den Größenverlauf",
            .aboutText: "Echtzeit-Überwachung von CPU-Auslastung (pro Kern), Speicher aller Arten und freiem Festplattenplatz in einem kleinen schwebenden Fenster.",
        ],
        "fr": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disque",
            .free: "libre",
            .used: "Utilisé",
            .appMemory: "Apps",
            .wired: "Résidente",
            .compressed: "Compressée",
            .cached: "Cache fichiers",
            .freeMemory: "Libre",
            .swap: "Swap",
            .pressure: "Pression",
            .pressureNormal: "Normale",
            .pressureWarning: "Avertissement",
            .pressureCritical: "Critique",
            .metricsSettings: "Réglages des mesures…",
            .uiSettings: "Réglages de l'interface…",
            .opacity: "Opacité",
            .contrast: "Contraste",
            .showCPU: "Charge CPU",
            .showCores: "Barres par cœur",
            .showMemory: "Mémoire",
            .showMemoryDetails: "Détail de la mémoire",
            .showDisks: "Disques",
            .updateInterval: "Actualiser toutes les",
            .menuBarMenu: "Barre des menus",
            .volumesSection: "Volumes",
            .activityMonitor: "Ouvrir le Moniteur d'activité",
            .floatingPanel: "Panneau flottant",
            .alwaysOnTop: "Toujours au premier plan",
            .compactPanel: "Panneau compact",
            .alignMenu: "Alignement",
            .alignLeft: "Gauche",
            .alignRight: "Droite",
            .launchAtLogin: "Lancer à l'ouverture de session",
            .language: "Langue",
            .about: "À propos…",
            .quit: "Quitter",
            .version: "Version",
            .openProjectFolder: "Ouvrir le dossier du projet",
            .loginItemError: "Impossible de modifier le démarrage automatique",
            .helpApp: "Mémoire occupée par les apps ouvertes et leurs données. Libérée à la fermeture, ou déplacée vers la mémoire compressée et le swap quand la RAM manque.",
            .helpWired: "Le noyau, les pilotes et tout ce qui ne doit jamais quitter la RAM. Ni compressible ni transférable sur disque : la seule part que macOS ne peut pas récupérer.",
            .helpCompressed: "Pages inactives réduites de moitié environ au lieu d'être écrites sur le disque. Bien moins coûteux que le swap : la décompression se fait en mémoire.",
            .helpCached: "Fichiers récemment utilisés conservés dans la RAM inoccupée pour les rouvrir instantanément. Rendue aux apps dès qu'elles la demandent — ce n'est pas une pénurie.",
            .helpFree: "RAM qui ne sert à rien du tout. macOS la garde volontairement proche de zéro : une mémoire inoccupée ne travaille pas, le surplus part dans le cache fichiers.",
            .helpSwap: "Pages écrites sur le disque quand la compression ne suffit plus. C'est le swap qui grimpe sans cesse qui rend un Mac lent.",
            .helpPressure: "Le verdict du système lui-même sur le manque de mémoire — plus fiable que le pourcentage utilisé.\n\nNormale — mémoire suffisante.\nAvertissement — macOS compresse et permute à plein régime ; les apps peuvent saccader.\nCritique — la mémoire s'épuise et le système peut commencer à fermer des apps.",
            .showFolders: "Dossiers",
            .foldersSettings: "Dossiers…",
            .addFolder: "Ajouter un dossier",
            .folderPath: "Chemin du dossier",
            .chooseFolder: "Choisir dans le Finder",
            .alias: "Alias",
            .rescan: "Analyser maintenant",
            .remove: "Retirer",
            .largestItems: "Plus gros éléments",
            .scanning: "Analyse…",
            .noAccess: "Aucun accès",
            .lastScan: "Dernière analyse",
            .scanNever: "Ne pas actualiser",
            .scanMinute: "Chaque minute",
            .scan5Minutes: "Toutes les 5 minutes",
            .scan10Minutes: "Toutes les 10 minutes",
            .scanHourly: "Toutes les heures",
            .scanDaily: "Chaque jour",
            .updatesMenu: "Mises à jour",
            .checkNow: "Vérifier maintenant",
            .checkAutomatically: "Vérifier automatiquement",
            .updateAvailable: "Version disponible :",
            .upToDate: "Vous avez la dernière version.",
            .checkFailed: "Impossible de joindre GitHub pour vérifier les mises à jour.",
            .openRelease: "Ouvrir la page de la version",
            .showGPU: "Charge GPU",
            .performanceCores: "Cœurs performance",
            .efficiencyCores: "Cœurs efficacité",
            .openInFinder: "Cliquer pour ouvrir dans le Finder",
            .eject: "Éjecter",
            .ejectFailed: "Impossible d’éjecter le volume",
            .history: "Historique",
            .historyDay: "Jour",
            .historyWeek: "Semaine",
            .historyMonth: "Mois",
            .historyQuarter: "Trimestre",
            .historyEmpty: "Aucune mesure pour l’instant. La taille est enregistrée à chaque analyse.",
            .historyChange: "évolution",
            .historyNotEnough: "Pas encore assez d’historique pour cette période",
            .historyClick: "Cliquer pour l’historique de taille",
            .aboutText: "Surveillance en temps réel de la charge CPU (par cœur), de la mémoire sous toutes ses formes et de l'espace disque libre dans une petite fenêtre flottante.",
        ],
        "it": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "liberi",
            .used: "Usato",
            .appMemory: "App",
            .wired: "Residente",
            .compressed: "Compressa",
            .cached: "Cache file",
            .freeMemory: "Libera",
            .swap: "Swap",
            .pressure: "Pressione",
            .pressureNormal: "Normale",
            .pressureWarning: "Avviso",
            .pressureCritical: "Critica",
            .metricsSettings: "Impostazioni metriche…",
            .uiSettings: "Impostazioni interfaccia…",
            .opacity: "Opacità",
            .contrast: "Contrasto",
            .showCPU: "Carico CPU",
            .showCores: "Barre per core",
            .showMemory: "Memoria",
            .showMemoryDetails: "Dettaglio memoria",
            .showDisks: "Dischi",
            .updateInterval: "Aggiorna ogni",
            .menuBarMenu: "Barra dei menu",
            .volumesSection: "Volumi",
            .activityMonitor: "Apri Monitoraggio Attività",
            .floatingPanel: "Pannello fluttuante",
            .alwaysOnTop: "Sempre in primo piano",
            .compactPanel: "Pannello compatto",
            .alignMenu: "Allineamento",
            .alignLeft: "Sinistra",
            .alignRight: "Destra",
            .launchAtLogin: "Avvia all'accesso",
            .language: "Lingua",
            .about: "Informazioni…",
            .quit: "Esci",
            .version: "Versione",
            .openProjectFolder: "Apri cartella del progetto",
            .loginItemError: "Impossibile modificare l'avvio automatico",
            .helpApp: "Memoria occupata dalle app aperte e dai loro dati. Si libera alla chiusura, oppure finisce in memoria compressa e swap quando la RAM scarseggia.",
            .helpWired: "Kernel, driver e tutto ciò che non può mai lasciare la RAM. Non si comprime né si scrive su disco: l'unica parte che macOS non riesce a recuperare.",
            .helpCompressed: "Pagine inattive compresse a circa metà invece di essere scritte su disco. Molto più economico dello swap: la decompressione avviene in memoria.",
            .helpCached: "File usati di recente tenuti nella RAM inutilizzata per riaprirli all'istante. Restituita alle app non appena la chiedono: non è una carenza.",
            .helpFree: "RAM non usata per nulla. macOS la tiene vicina a zero di proposito: la memoria inattiva non lavora, quindi l'avanzo va alla cache dei file.",
            .helpSwap: "Pagine scritte su disco quando la compressione non basta più. È lo swap che cresce di continuo a rendere lento un Mac.",
            .helpPressure: "Il verdetto del sistema stesso sulla carenza di memoria: segnale migliore della percentuale usata.\n\nNormale — memoria sufficiente.\nAvviso — macOS comprime e fa swap a pieno ritmo; le app possono scattare.\nCritica — la memoria sta finendo e il sistema può iniziare a chiudere le app.",
            .showFolders: "Cartelle",
            .foldersSettings: "Cartelle…",
            .addFolder: "Aggiungi cartella",
            .folderPath: "Percorso della cartella",
            .chooseFolder: "Scegli nel Finder",
            .alias: "Alias",
            .rescan: "Analizza ora",
            .remove: "Rimuovi",
            .largestItems: "Elementi più grandi",
            .scanning: "Analisi…",
            .noAccess: "Nessun accesso",
            .lastScan: "Ultima analisi",
            .scanNever: "Non aggiornare",
            .scanMinute: "Ogni minuto",
            .scan5Minutes: "Ogni 5 minuti",
            .scan10Minutes: "Ogni 10 minuti",
            .scanHourly: "Ogni ora",
            .scanDaily: "Ogni giorno",
            .updatesMenu: "Aggiornamenti",
            .checkNow: "Controlla ora",
            .checkAutomatically: "Controlla automaticamente",
            .updateAvailable: "Versione disponibile:",
            .upToDate: "Hai già l'ultima versione.",
            .checkFailed: "Impossibile raggiungere GitHub per controllare gli aggiornamenti.",
            .openRelease: "Apri la pagina della versione",
            .showGPU: "Carico GPU",
            .performanceCores: "Core performance",
            .efficiencyCores: "Core efficienza",
            .openInFinder: "Clic per aprire nel Finder",
            .eject: "Espelli",
            .ejectFailed: "Impossibile espellere il volume",
            .history: "Cronologia",
            .historyDay: "Giorno",
            .historyWeek: "Settimana",
            .historyMonth: "Mese",
            .historyQuarter: "Trimestre",
            .historyEmpty: "Ancora nessuna misurazione. La dimensione viene registrata a ogni analisi.",
            .historyChange: "variazione",
            .historyNotEnough: "Cronologia ancora insufficiente per questo periodo",
            .historyClick: "Clic per la cronologia delle dimensioni",
            .aboutText: "Monitoraggio in tempo reale del carico della CPU (per core), della memoria di ogni tipo e dello spazio libero su disco in una piccola finestra flottante.",
        ],
        "pt": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "livres",
            .used: "Usado",
            .appMemory: "Apps",
            .wired: "Residente",
            .compressed: "Comprimida",
            .cached: "Cache de arquivos",
            .freeMemory: "Livre",
            .swap: "Swap",
            .pressure: "Pressão",
            .pressureNormal: "Normal",
            .pressureWarning: "Alerta",
            .pressureCritical: "Crítica",
            .metricsSettings: "Ajustes de métricas…",
            .uiSettings: "Ajustes de interface…",
            .opacity: "Opacidade",
            .contrast: "Contraste",
            .showCPU: "Carga da CPU",
            .showCores: "Barras por núcleo",
            .showMemory: "Memória",
            .showMemoryDetails: "Detalhamento da memória",
            .showDisks: "Discos",
            .updateInterval: "Atualizar a cada",
            .menuBarMenu: "Barra de menus",
            .volumesSection: "Volumes",
            .activityMonitor: "Abrir Monitor de Atividade",
            .floatingPanel: "Painel flutuante",
            .alwaysOnTop: "Sempre visível",
            .compactPanel: "Painel compacto",
            .alignMenu: "Alinhamento",
            .alignLeft: "Esquerda",
            .alignRight: "Direita",
            .launchAtLogin: "Iniciar ao fazer login",
            .language: "Idioma",
            .about: "Sobre…",
            .quit: "Sair",
            .version: "Versão",
            .openProjectFolder: "Abrir pasta do projeto",
            .loginItemError: "Não foi possível alterar a inicialização automática",
            .helpApp: "Memória ocupada pelos apps abertos e seus dados. Liberada ao fechar o app, ou empurrada para memória comprimida e swap quando falta RAM.",
            .helpWired: "Kernel, drivers e tudo o que nunca pode sair da RAM. Não dá para comprimir nem mandar ao disco: a única parte que o macOS não consegue recuperar.",
            .helpCompressed: "Páginas inativas espremidas para cerca de metade em vez de irem para o disco. Bem mais barato que swap: descomprimir acontece na memória.",
            .helpCached: "Arquivos usados há pouco mantidos na RAM ociosa para reabrir na hora. Devolvida aos apps assim que eles pedem — não é escassez.",
            .helpFree: "RAM que não faz nada. O macOS a mantém perto de zero de propósito: memória ociosa não trabalha, então a sobra vira cache de arquivos.",
            .helpSwap: "Páginas gravadas no disco quando a compressão já não basta. É o swap crescendo sem parar que deixa o Mac lento.",
            .helpPressure: "O veredito do próprio sistema sobre falta de memória — sinal melhor que a porcentagem usada.\n\nNormal — memória suficiente.\nAlerta — o macOS comprime e faz swap a todo vapor; os apps podem travar.\nCrítica — a memória está acabando e o sistema pode começar a fechar apps.",
            .showFolders: "Pastas",
            .foldersSettings: "Pastas…",
            .addFolder: "Adicionar pasta",
            .folderPath: "Caminho da pasta",
            .chooseFolder: "Escolher no Finder",
            .alias: "Apelido",
            .rescan: "Analisar agora",
            .remove: "Remover",
            .largestItems: "Maiores itens",
            .scanning: "Analisando…",
            .noAccess: "Sem acesso",
            .lastScan: "Última análise",
            .scanNever: "Não atualizar",
            .scanMinute: "A cada minuto",
            .scan5Minutes: "A cada 5 minutos",
            .scan10Minutes: "A cada 10 minutos",
            .scanHourly: "A cada hora",
            .scanDaily: "A cada dia",
            .updatesMenu: "Atualizações",
            .checkNow: "Verificar agora",
            .checkAutomatically: "Verificar automaticamente",
            .updateAvailable: "Versão disponível:",
            .upToDate: "Você já tem a versão mais recente.",
            .checkFailed: "Não foi possível acessar o GitHub para verificar atualizações.",
            .openRelease: "Abrir a página da versão",
            .showGPU: "Carga da GPU",
            .performanceCores: "Núcleos de desempenho",
            .efficiencyCores: "Núcleos de eficiência",
            .openInFinder: "Clique para abrir no Finder",
            .eject: "Ejetar",
            .ejectFailed: "Não foi possível ejetar o volume",
            .history: "Histórico",
            .historyDay: "Dia",
            .historyWeek: "Semana",
            .historyMonth: "Mês",
            .historyQuarter: "Trimestre",
            .historyEmpty: "Ainda sem medições. O tamanho é registrado em cada análise.",
            .historyChange: "variação",
            .historyNotEnough: "Ainda não há histórico suficiente para este período",
            .historyClick: "Clique para ver o histórico de tamanho",
            .aboutText: "Monitoramento em tempo real da carga da CPU (por núcleo), da memória de todos os tipos e do espaço livre em disco em uma pequena janela flutuante.",
        ],
        // Português europeu. Отдельная таблица, а не правка бразильской: разница
        // не только в словах (ficheiro / arquivo, definições / ajustes), но и в
        // грамматике — длящееся действие в pt-PT это «a analisar», а не
        // «analisando». Кроме того «apelido» в Португалии значит «фамилия», так
        // что поле псевдонима здесь называется иначе. Оба варианта живут рядом.
        "pt-PT": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "RAM",
            .disk: "Disco",
            .free: "livres",
            .used: "Usado",
            .appMemory: "Apps",
            .wired: "Residente",
            .compressed: "Comprimida",
            .cached: "Cache de ficheiros",
            .freeMemory: "Livre",
            .swap: "Swap",
            .pressure: "Pressão",
            .pressureNormal: "Normal",
            .pressureWarning: "Alerta",
            .pressureCritical: "Crítica",
            .metricsSettings: "Definições de métricas…",
            .uiSettings: "Definições de interface…",
            .opacity: "Opacidade",
            .contrast: "Contraste",
            .showCPU: "Carga do CPU",
            .showCores: "Barras por núcleo",
            .showMemory: "Memória",
            .showMemoryDetails: "Detalhe da memória",
            .showDisks: "Discos",
            .updateInterval: "Atualizar a cada",
            .menuBarMenu: "Barra de menus",
            .volumesSection: "Volumes",
            .activityMonitor: "Abrir Monitor de Atividade",
            .floatingPanel: "Painel flutuante",
            .alwaysOnTop: "Sempre visível",
            .compactPanel: "Painel compacto",
            .alignMenu: "Alinhamento",
            .alignLeft: "Esquerda",
            .alignRight: "Direita",
            .launchAtLogin: "Abrir ao iniciar sessão",
            .language: "Idioma",
            .about: "Sobre…",
            .quit: "Sair",
            .version: "Versão",
            .openProjectFolder: "Abrir pasta do projeto",
            .loginItemError: "Não foi possível alterar a abertura automática",
            .helpApp: "Memória ocupada pelas aplicações abertas e pelos seus dados. Libertada ao fechar a aplicação, ou empurrada para memória comprimida e swap quando falta RAM.",
            .helpWired: "Kernel, drivers e tudo o que nunca pode sair da RAM. Não é possível comprimi-la nem enviá-la para o disco: a única parte que o macOS não consegue recuperar.",
            .helpCompressed: "Páginas inativas espremidas para cerca de metade em vez de irem para o disco. Bem mais barato do que swap: descomprimir acontece na memória.",
            .helpCached: "Ficheiros usados há pouco mantidos na RAM ociosa para reabrirem de imediato. Devolvida às aplicações assim que estas a pedem — não é escassez.",
            .helpFree: "RAM que não faz nada. O macOS mantém-na perto de zero de propósito: memória ociosa não trabalha, por isso a sobra passa a cache de ficheiros.",
            .helpSwap: "Páginas gravadas no disco quando a compressão já não chega. É o swap a crescer sem parar que deixa o Mac lento.",
            .helpPressure: "O veredito do próprio sistema sobre a falta de memória — melhor sinal do que a percentagem usada.\n\nNormal — memória suficiente.\nAlerta — o macOS comprime e faz swap a todo o vapor; as aplicações podem bloquear.\nCrítica — a memória está a acabar e o sistema pode começar a fechar aplicações.",
            .showFolders: "Pastas",
            .foldersSettings: "Pastas…",
            .addFolder: "Adicionar pasta",
            .folderPath: "Caminho da pasta",
            .chooseFolder: "Escolher no Finder",
            .alias: "Nome alternativo",
            .rescan: "Analisar agora",
            .remove: "Remover",
            .largestItems: "Maiores itens",
            .scanning: "A analisar…",
            .noAccess: "Sem acesso",
            .lastScan: "Última análise",
            .scanNever: "Não atualizar",
            .scanMinute: "A cada minuto",
            .scan5Minutes: "A cada 5 minutos",
            .scan10Minutes: "A cada 10 minutos",
            .scanHourly: "A cada hora",
            .scanDaily: "A cada dia",
            .updatesMenu: "Atualizações",
            .checkNow: "Verificar agora",
            .checkAutomatically: "Verificar automaticamente",
            .updateAvailable: "Versão disponível:",
            .upToDate: "Já tem a versão mais recente.",
            .checkFailed: "Não foi possível aceder ao GitHub para verificar atualizações.",
            .openRelease: "Abrir a página da versão",
            .showGPU: "Carga do GPU",
            .performanceCores: "Núcleos de desempenho",
            .efficiencyCores: "Núcleos de eficiência",
            .openInFinder: "Clique para abrir no Finder",
            .eject: "Ejetar",
            .ejectFailed: "Não foi possível ejetar o volume",
            .history: "Histórico",
            .historyDay: "Dia",
            .historyWeek: "Semana",
            .historyMonth: "Mês",
            .historyQuarter: "Trimestre",
            .historyEmpty: "Ainda sem medições. O tamanho é registado em cada análise.",
            .historyChange: "variação",
            .historyNotEnough: "Ainda não há histórico suficiente para este período",
            .historyClick: "Clique para ver o histórico de tamanho",
            .aboutText: "Monitorização em tempo real da carga do CPU (por núcleo), da memória de todos os tipos e do espaço livre em disco numa pequena janela flutuante.",
        ],
        "zh": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "内存",
            .disk: "磁盘",
            .free: "可用",
            .used: "已用",
            .appMemory: "应用内存",
            .wired: "联动内存",
            .compressed: "已压缩",
            .cached: "文件缓存",
            .freeMemory: "空闲",
            .swap: "交换区",
            .pressure: "内存压力",
            .pressureNormal: "正常",
            .pressureWarning: "警告",
            .pressureCritical: "严重",
            .metricsSettings: "指标设置…",
            .uiSettings: "界面设置…",
            .opacity: "不透明度",
            .contrast: "对比色",
            .showCPU: "CPU 负载",
            .showCores: "每核心柱状图",
            .showMemory: "内存",
            .showMemoryDetails: "内存明细",
            .showDisks: "磁盘",
            .updateInterval: "刷新间隔",
            .menuBarMenu: "菜单栏",
            .volumesSection: "宗卷",
            .activityMonitor: "打开活动监视器",
            .floatingPanel: "悬浮面板",
            .alwaysOnTop: "置顶显示",
            .compactPanel: "紧凑面板",
            .alignMenu: "对齐",
            .alignLeft: "左",
            .alignRight: "右",
            .launchAtLogin: "登录时启动",
            .language: "语言",
            .about: "关于…",
            .quit: "退出",
            .version: "版本",
            .openProjectFolder: "打开项目文件夹",
            .loginItemError: "无法更改登录启动项",
            .helpApp: "运行中的应用及其数据占用的内存。应用退出时释放；内存紧张时会被转入压缩内存和交换区。",
            .helpWired: "内核、驱动以及绝不能离开内存的内容。既不能压缩也不能写入磁盘——内存紧张时 macOS 唯一无法回收的部分。",
            .helpCompressed: "不活跃的页面被压缩到约一半大小，而不是写入磁盘。比交换区便宜得多：解压在内存中完成。",
            .helpCached: "最近用过的文件留在闲置内存里，再次打开即可瞬间完成。应用一需要就立刻归还——这不是内存不足。",
            .helpFree: "完全没有被使用的内存。macOS 有意让它接近零：闲置的内存不干活，多余容量宁可拿去做文件缓存。",
            .helpSwap: "压缩已经不够用时写到磁盘上的页面。交换区持续增长正是 Mac 变慢的原因。",
            .helpPressure: "系统自己对「应用是否内存不足」的判断，比占用百分比更可靠。\n\n正常——内存充足。\n警告——macOS 正在大量压缩和交换，应用可能开始卡顿。\n严重——内存即将耗尽，系统可能开始关闭应用。",
            .showFolders: "文件夹",
            .foldersSettings: "文件夹…",
            .addFolder: "添加文件夹",
            .folderPath: "文件夹路径",
            .chooseFolder: "在访达中选择",
            .alias: "别名",
            .rescan: "立即扫描",
            .remove: "移除",
            .largestItems: "最大的项目",
            .scanning: "正在扫描…",
            .noAccess: "无访问权限",
            .lastScan: "上次扫描",
            .scanNever: "不更新",
            .scanMinute: "每分钟",
            .scan5Minutes: "每 5 分钟",
            .scan10Minutes: "每 10 分钟",
            .scanHourly: "每小时",
            .scanDaily: "每天",
            .updatesMenu: "更新",
            .checkNow: "立即检查",
            .checkAutomatically: "自动检查",
            .updateAvailable: "有新版本：",
            .upToDate: "已是最新版本。",
            .checkFailed: "无法连接 GitHub 检查更新。",
            .openRelease: "打开发布页面",
            .showGPU: "GPU 负载",
            .performanceCores: "性能核心",
            .efficiencyCores: "能效核心",
            .openInFinder: "点按可在访达中打开",
            .eject: "推出",
            .ejectFailed: "无法推出宗卷",
            .history: "历史",
            .historyDay: "天",
            .historyWeek: "周",
            .historyMonth: "月",
            .historyQuarter: "季度",
            .historyEmpty: "尚无测量数据。每次扫描都会记录大小。",
            .historyChange: "变化",
            .historyNotEnough: "此时间范围的历史数据还不够",
            .historyClick: "点按查看大小历史",
            .aboutText: "在小型悬浮窗口中实时显示 CPU 负载（分核心）、各类内存占用和磁盘可用空间。",
        ],
        "ja": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "メモリ",
            .disk: "ディスク",
            .free: "空き",
            .used: "使用中",
            .appMemory: "アプリ",
            .wired: "確保中",
            .compressed: "圧縮済み",
            .cached: "ファイルキャッシュ",
            .freeMemory: "空き",
            .swap: "スワップ",
            .pressure: "メモリ負荷",
            .pressureNormal: "通常",
            .pressureWarning: "警告",
            .pressureCritical: "危険",
            .metricsSettings: "計測項目の設定…",
            .uiSettings: "UI設定…",
            .opacity: "不透明度",
            .contrast: "コントラスト",
            .showCPU: "CPU使用率",
            .showCores: "コア別バー",
            .showMemory: "メモリ",
            .showMemoryDetails: "メモリ内訳",
            .showDisks: "ディスク",
            .updateInterval: "更新間隔",
            .menuBarMenu: "メニューバー",
            .volumesSection: "ボリューム",
            .activityMonitor: "アクティビティモニタを開く",
            .floatingPanel: "フローティングパネル",
            .alwaysOnTop: "常に最前面",
            .compactPanel: "コンパクトパネル",
            .alignMenu: "配置",
            .alignLeft: "左",
            .alignRight: "右",
            .launchAtLogin: "ログイン時に起動",
            .language: "言語",
            .about: "このアプリについて…",
            .quit: "終了",
            .version: "バージョン",
            .openProjectFolder: "プロジェクトフォルダを開く",
            .loginItemError: "ログイン項目を変更できませんでした",
            .helpApp: "実行中のアプリとそのデータが使うメモリ。アプリの終了で解放され、不足時は圧縮メモリやスワップに送られます。",
            .helpWired: "カーネルやドライバなど、メモリから決して出せない領域。圧縮もスワップもできず、逼迫時に macOS が唯一回収できない部分です。",
            .helpCompressed: "非アクティブなページをディスクに書かず、約半分に圧縮したもの。展開はメモリ内で済むため、スワップよりずっと安上がりです。",
            .helpCached: "最近使ったファイルを空きメモリに残し、開き直しを一瞬にする仕組み。アプリが求めた瞬間に返されるので、不足ではありません。",
            .helpFree: "まったく使われていないメモリ。macOS は意図的にゼロ近くに保ちます。遊んでいるメモリは働かないので、余りはファイルキャッシュに回されます。",
            .helpSwap: "圧縮では足りなくなったときにディスクへ書き出されたページ。スワップの増加こそが Mac を重くする原因です。",
            .helpPressure: "メモリが足りているかどうかについてのシステム自身の判定。使用率より信頼できる指標です。\n\n通常 — メモリに余裕あり。\n警告 — 圧縮とスワップが増えており、アプリが引っかかることがあります。\n危険 — メモリが尽きかけており、システムがアプリを終了させる場合があります。",
            .showFolders: "フォルダ",
            .foldersSettings: "フォルダ…",
            .addFolder: "フォルダを追加",
            .folderPath: "フォルダのパス",
            .chooseFolder: "Finderで選択",
            .alias: "別名",
            .rescan: "今すぐスキャン",
            .remove: "削除",
            .largestItems: "大きい項目",
            .scanning: "スキャン中…",
            .noAccess: "アクセスできません",
            .lastScan: "最終スキャン",
            .scanNever: "更新しない",
            .scanMinute: "1分ごと",
            .scan5Minutes: "5分ごと",
            .scan10Minutes: "10分ごと",
            .scanHourly: "1時間ごと",
            .scanDaily: "1日ごと",
            .updatesMenu: "アップデート",
            .checkNow: "今すぐ確認",
            .checkAutomatically: "自動的に確認",
            .updateAvailable: "新しいバージョン:",
            .upToDate: "最新バージョンです。",
            .checkFailed: "GitHub に接続できず、アップデートを確認できませんでした。",
            .openRelease: "リリースページを開く",
            .showGPU: "GPU使用率",
            .performanceCores: "高性能コア",
            .efficiencyCores: "高効率コア",
            .openInFinder: "クリックでFinderに表示",
            .eject: "取り出す",
            .ejectFailed: "ボリュームを取り出せませんでした",
            .history: "履歴",
            .historyDay: "日",
            .historyWeek: "週",
            .historyMonth: "月",
            .historyQuarter: "四半期",
            .historyEmpty: "まだ計測データがありません。サイズはスキャンごとに記録されます。",
            .historyChange: "変化",
            .historyNotEnough: "この期間の履歴はまだ足りません",
            .historyClick: "クリックでサイズの履歴",
            .aboutText: "CPU使用率（コア別）、あらゆる種類のメモリ、ディスクの空き容量を小さなフローティングウィンドウでリアルタイムに表示します。",
        ],
        "ko": [
            .cpu: "CPU",
            .gpu: "GPU",
            .memory: "메모리",
            .disk: "디스크",
            .free: "여유",
            .used: "사용 중",
            .appMemory: "앱 메모리",
            .wired: "고정됨",
            .compressed: "압축됨",
            .cached: "파일 캐시",
            .freeMemory: "여유",
            .swap: "스왑",
            .pressure: "메모리 압력",
            .pressureNormal: "보통",
            .pressureWarning: "경고",
            .pressureCritical: "위험",
            .metricsSettings: "측정 항목 설정…",
            .uiSettings: "UI 설정…",
            .opacity: "불투명도",
            .contrast: "대비",
            .showCPU: "CPU 사용량",
            .showCores: "코어별 막대",
            .showMemory: "메모리",
            .showMemoryDetails: "메모리 세부 내역",
            .showDisks: "디스크",
            .updateInterval: "업데이트 주기",
            .menuBarMenu: "메뉴 막대",
            .volumesSection: "볼륨",
            .activityMonitor: "활성 상태 보기 열기",
            .floatingPanel: "플로팅 패널",
            .alwaysOnTop: "항상 위에 표시",
            .compactPanel: "컴팩트 패널",
            .alignMenu: "정렬",
            .alignLeft: "왼쪽",
            .alignRight: "오른쪽",
            .launchAtLogin: "로그인 시 시작",
            .language: "언어",
            .about: "정보…",
            .quit: "종료",
            .version: "버전",
            .openProjectFolder: "프로젝트 폴더 열기",
            .loginItemError: "로그인 항목을 변경할 수 없습니다",
            .helpApp: "실행 중인 앱과 그 데이터가 차지한 메모리. 앱을 종료하면 해제되고, 부족해지면 압축 메모리와 스왑으로 밀려납니다.",
            .helpWired: "커널과 드라이버 등 절대 메모리를 떠날 수 없는 영역. 압축도 스왑도 불가능해, 부족할 때 macOS가 유일하게 회수하지 못하는 부분입니다.",
            .helpCompressed: "비활성 페이지를 디스크에 쓰는 대신 약 절반 크기로 압축한 것. 압축 해제가 메모리에서 끝나 스왑보다 훨씬 저렴합니다.",
            .helpCached: "최근 사용한 파일을 놀고 있는 메모리에 두어 다시 열 때 즉시 뜨게 합니다. 앱이 요구하면 바로 돌려주므로 부족한 상태가 아닙니다.",
            .helpFree: "아무 데도 쓰이지 않는 메모리. macOS는 일부러 0에 가깝게 유지합니다. 놀고 있는 메모리는 일을 하지 않으니 여유분은 파일 캐시로 돌립니다.",
            .helpSwap: "압축만으로 부족할 때 디스크로 내보낸 페이지. 스왑이 계속 늘어나는 것이 Mac이 느려지는 이유입니다.",
            .helpPressure: "앱에 메모리가 부족한지에 대한 시스템 자체의 판정으로, 사용률보다 믿을 만한 신호입니다.\n\n보통 — 메모리 충분.\n경고 — macOS가 압축과 스왑을 크게 늘리는 중이며 앱이 끊길 수 있습니다.\n위험 — 메모리가 바닥나는 중이라 시스템이 앱을 종료할 수 있습니다.",
            .showFolders: "폴더",
            .foldersSettings: "폴더…",
            .addFolder: "폴더 추가",
            .folderPath: "폴더 경로",
            .chooseFolder: "Finder에서 선택",
            .alias: "별칭",
            .rescan: "지금 검사",
            .remove: "제거",
            .largestItems: "가장 큰 항목",
            .scanning: "검사 중…",
            .noAccess: "접근 불가",
            .lastScan: "마지막 검사",
            .scanNever: "업데이트 안 함",
            .scanMinute: "1분마다",
            .scan5Minutes: "5분마다",
            .scan10Minutes: "10분마다",
            .scanHourly: "1시간마다",
            .scanDaily: "1일마다",
            .updatesMenu: "업데이트",
            .checkNow: "지금 확인",
            .checkAutomatically: "자동으로 확인",
            .updateAvailable: "새 버전:",
            .upToDate: "최신 버전을 사용 중입니다.",
            .checkFailed: "GitHub에 연결하지 못해 업데이트를 확인할 수 없습니다.",
            .openRelease: "릴리스 페이지 열기",
            .showGPU: "GPU 사용량",
            .performanceCores: "성능 코어",
            .efficiencyCores: "효율 코어",
            .openInFinder: "클릭하면 Finder에서 열림",
            .eject: "추출",
            .ejectFailed: "볼륨을 추출할 수 없습니다",
            .history: "기록",
            .historyDay: "일",
            .historyWeek: "주",
            .historyMonth: "월",
            .historyQuarter: "분기",
            .historyEmpty: "아직 측정값이 없습니다. 크기는 검사할 때마다 기록됩니다.",
            .historyChange: "변화",
            .historyNotEnough: "이 기간의 기록이 아직 충분하지 않습니다",
            .historyClick: "클릭하면 크기 기록",
            .aboutText: "CPU 사용량(코어별), 모든 종류의 메모리, 디스크 여유 공간을 작은 플로팅 창에서 실시간으로 보여줍니다.",
        ],
    ]
}

#if DEV_BUILD
// Dev-примечания для About: только в сборке с -dev, в публичный бинарник не попадают.
extension L10n {
    func devSuffix() -> String {
        lang == "ru"
            ? "Локальная dev-сборка этого компьютера.\nСобрано с помощью Claude Code.\n\nПапка проекта:\n{path}"
            : "Local dev build for this Mac.\nBuilt with Claude Code.\n\nProject folder:\n{path}"
    }
}
#endif
